### ISSUE TITLE
API Keys instead of OAUTH2 as an option ?

### ISSUE THREAD

**Issue by rmills9** [revk/NOTSCO#10]
Any way of adding API Keys as a way of auth for the simulator rather than OAUTH2 ?

Sample Format:
POST /post HTTP/1.1
https://{fqdn}/letterbox/{version}
apikey: <API_key_value>

**Comment by revk** [comment]
Ok my concern is the API key has a load of baggage I think, something about signed stuff.

I could easily do a fixed configured `apikey` value each way if that makes sense?

**Comment by rmills9** [comment]
Yeah sure. Sounds good

**Comment by revk** [comment]
Ok leave with me - I suspect to the test system the API key will be the same as the client secret and same the other way, i.e. if no client ID we do API key each way.

Does that make sense?

**Comment by rmills9** [comment]
Yeah brill. Thanks appreciate it.

**Comment by revk** [comment]
OK maybe tomorrow. Are you in a position to test with it?

**Comment by rmills9** [comment]
Yeah no worries. Yeah all ready to go. :)

**Comment by revk** [comment]
OK tomorrow, and should pre pretty easy to do.

**Comment by rmills9** [comment]
Wicked. hahaha yeah bit stupid the way they're doing it tbh.

**Comment by revk** [comment]
I'll re-read the TOTSCO specs on API keys, and see what I can do this morning.

**Comment by revk** [comment]
OK try that, leave client ID blank and put the APIKEY in the secret.
