### ISSUE TITLE
UPRN is zero-padded

### ISSUE THREAD

**Issue by slimey99uk** [revk/NOTSCO#16]
Page 8 of Draft 1.1 of OTS Message Specification says, for address/uprn:

"A UPRN can be up to 12 digits long. For the avoidance of doubt, do not include any leading zeroes."

NOTSCO is zero-padding to 12 digits:

"residentialSwitchMatchRequest":{
  "grcpBrandName":"Bogons",
  "name":"Lockhart",
  "address":{
   "uprn":"010033399999",
   [...]

**Comment by revk** [comment]
Oooh, you might have me there!

I thought it was conventional to zero pad UPRNs, and did not spot the TOTSCO note. I note the UPRNs from O/S seem to be zero padded.

I'll fix and add a test for that too.

(Tomorrow)
