### ISSUE TITLE
OAUTH2 client does not check content-type on response

### ISSUE THREAD

**Issue by slimey99uk** [revk/NOTSCO#18]
On actual TOTSCO (at least pre-prod), OAUTH2 fails if the response with the token does not set "Content-Type: application/json"

In fact, it fails silently, and just sends "Authorisation: Bearer" without a token on messages from the hub.

Worse, simulator testing does not enforce content-type.

It would be good if NOTSCO flagged if content-type is not set correctly on OAUTH2 replies.

**Comment by revk** [comment]
I am glad you found the cause, I did wonder if that was the case…I use a long standing library for this, so need to check the best way to flag this o NOTSCO to check without breaking anything else, and check the RFC.But I totally agree NOTSCO should pick this up.On 8 Sep 2024, at 20:53, Simon Lockhart ***@***.***> wrote:﻿
On actual TOTSCO (at least pre-prod), OAUTH2 fails if the response with the token does not set "Content-Type: application/json"
In fact, it fails silently, and just sends "Authorisation: Bearer" without a token on messages from the hub.
Worse, simulator testing does not enforce content-type.
It would be good if NOTSCO flagged if content-type is not set correctly on OAUTH2 replies.

**Comment by revk** [comment]
Should not check, please do test.
