### ISSUE TITLE
APIKEY auth

### ISSUE THREAD

**Issue by talkstraightuk** [revk/NOTSCO#19]
**Describe the bug**

Unable to use apikey auth to communicate with our API.

In "Messages from the simulator" section I've populated API and CLIENT SECRET fields and left the OAUTH2 token (url) and  CLIENTID fields blank as directed. 

On the home page it continues to show two warning messages

- You have not set a token API yet.
- You have not set a Client ID yet.

These disappear when filling in the oauth2 fields as expected, which of course then causes the API to use oauth2.

I suspect this is just some verification issue and I definitely had this working a couple of weeks ago.

**Expected behavior**

Ability to post messages to apikey authed API.

**Additional context**

If it's me missing something, many apologies.  It's a great setup and a fantastic help for getting totsco working, many thanks.

**Comment by revk** [comment]
Which company so I can check? It should not offer OAUTH URL or client ID if you select API KEY so that sounds very odd.

**Comment by revk** [comment]
Ah, Ok you need to select auth method APIKEY now, in Connection and authentication, I thought I made it backwards compatible when this was changed.

**Comment by talkstraightuk** [comment]
Ah I see, but if I choose this, it hides the creds for doing oauth2 to notsco.

**Comment by revk** [comment]
Well, yes, using APIKEY not OAUTH2, or am I missing something?

**Comment by talkstraightuk** [comment]
I'm using oauth2 to talk to notsco but I want notsco to use apikey to talk to us

**Comment by revk** [comment]
OK that is a thing?

I had no idea they offer that.

OK, I need to work out that as an option - I am rather busy, but I'll see what I can do.

**Comment by revk** [comment]
Thinking about it, I should be able to make the receiving side use either regardless. But need it to advise the OAUTH creds.

Do they work at all when APIKEY is selected? I may be easy to allow them to.

**Comment by talkstraightuk** [comment]
When I used the system a few weeks ago it worked fine, I just think you've added some extra validation to stop it making calls when those fields are blank.

**Comment by revk** [comment]
OK try now, set to APIKEY, and should allow both, I hope.

**Comment by talkstraightuk** [comment]
Fantastic, just tested with the Bad Messages and got a request through.

Many thanks for the swift resolution.

**Comment by revk** [comment]
I had not idea that was an option. TOTSCO do not make it clear!

**Comment by talkstraightuk** [comment]
I'm praying that it does work that way now that you mention it as I can't be bothered to sort oauth2 out!  I've dropped them a mail to double check.

Nothing in this entire process has been clear, the docs are a nightmare.  Notsco has been a testing godsend!

**Comment by revk** [comment]
Thanks for confirming, so what we are doing now is OK?

**Comment by talkstraightuk** [comment]
Yeah spot on, works great for my setup.  I suppose there is the possibility someone might want notsco to be apikey and them be oauth2.

**Comment by revk** [comment]
Oh I see, so allow APIKEY setting even when OAUTH2 selected. Yeh, could add that.
