### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by stevenhowes** [revk/NOTSCO#3]
**Describe the bug**
If sending to an invalid RCPID the error returned is "Unknown **of** invalid destination". 

**Specification reference**
1.1a - CLEAN page 15

**Message exchange**

TX
`{
 "envelope":{
  "source":{
   "type":"RCPID",
   "identity":"RPPW",
   "correlationID":"b9638698-2c99-11ef-aaa-aaaaaaa"
  },
  "destination":{
   "type":"RCPID",
   "identity":"TEST"
  },
  "routingID":"residentialSwitchMatchRequest"
 },
 "residentialSwitchMatchRequest":{
  "":"Fakebrand",
  "name":"Smith",
  "account":"Test",
  "address":{
   "uprn":"11111",
   "addressLines":[
    "12 Three Street"
   ],
   "postTown":"Balamory",
   "postCode":"AA1 1AA"
  },
  "services":[
   {
    "serviceType":"IAS",
    "action":"cease"
   },
   {
    "serviceType":"NBICS",
    "serviceIdentifier":"01234567890",
    "action":"identify"
   }
  ]
 }
}`

RX
`{
 "errorCode":9001,
 "errorText":"Unknown of invalid destination."
}`

**Expected behavior**
I think this should be "Unknown **or** invalid destination"

**Comment by revk** [comment]
I have also added a directory to the connection page, so you can see what RCPIDs are valid.

**Comment by revk** [comment]
I have also added `TEST` as a valid RCPID.
