### ISSUE TITLE
Connection Settings Letterbox path typo

### ISSUE THREAD

**Issue by surfermarty** [revk/NOTSCO#8]
On the 'Connection and authentication' settings page in the 'Messages from the simulator' section, the placeholder text says the API URL usually ends .../port, where as the TOTSCo API document says it's .../post

Might be just a typo and as your code is able to deal with any URL, it's purely cosmetic.

Feel free to reject this if it's because there is an inconsistency in the API document from TOTSCo!

I also feel bad reporting it as a bug - it's not really - my eyes just tripped over it as I've got this and the API document opened side by side....

**Comment by revk** [comment]
LOL, typo, will fix

**Comment by revk** [comment]
Yes, the spec says...

```
2.1.2 URI format
The API URI format provided by the TOTSCo Hub, and each RCP (or MAP) will conform to the following
convention.
https://{fqdn}/letterbox/{version}/post
```

But they allow any URL your side, which is crazy. But that is why we allow any URL.

Fixed.
